#!/bin/sh
# /etc/hotplug.d/button/50-sing-box-switch
# Bind sing-box VPN client to the GL.iNet physical mode switch.
# Active only when sing-box.config.bind_switch=1 AND the GL.iNet switch-button
# is not already bound to a known native function (wireguard/openvpn/etc.).

[ "$BUTTON" = "switch" ] || exit 0

. /lib/functions.sh
config_load 'sing-box'
config_get_bool bind_switch config bind_switch 0
[ "$bind_switch" = "1" ] || exit 0

sw_func=$(uci -q get switch-button.@main[0].func 2>/dev/null)
case "$sw_func" in
	wireguard|openvpn|tor|adguardhome|wifi|repeater|cellular)
		logger -t sing-box-switch "skip: switch-button bound to '$sw_func'"
		exit 0
		;;
esac

logger -t sing-box-switch "physical switch action=$ACTION"

case "$ACTION" in
	pressed)
		/etc/init.d/sing-box start
		;;
	released)
		/etc/init.d/sing-box stop
		# Physical OFF means user wants normal routing; drop killswitch
		# even if UCI killswitch=1.
		ip rule del priority 5500 2>/dev/null
		;;
esac
